#!/bin/bash

python3 /usercode/src/app.py > /dev/null 2>&1 &
API_PID=$!

sleep 0.5

python3 /usercode/src/client.py
CLIENT_EXIT=$?

# Nettoyer
kill $API_PID 2>/dev/null
wait $API_PID 2>/dev/null 

exit $CLIENT_EXIT 